import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { readFileSync } from 'node:fs'

const { version } = JSON.parse(readFileSync(new URL('../../package.json', import.meta.url), 'utf8')) as { version: string }

test('storage and workload projects stay independent through navigation, reload and explicit transfers', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('./')
  await expect(page.getByText(`Plan your cluster · v${version}`, { exact: true })).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('planning-overview.png'), fullPage: true })
  await page.getByRole('link', { name: 'Storage Sizing', exact: true }).click()
  await page.getByLabel('Active project name').fill('Storage only')
  await page.getByRole('link', { name: 'Hardware & Drives', exact: true }).click()
  const nodes = page.getByRole('group', { name: 'Number of nodes', exact: true }).getByRole('spinbutton')
  await nodes.fill('6')
  await page.getByRole('link', { name: 'Workload Planning', exact: true }).click()
  await page.getByRole('link', { name: /Assess existing hardware/ }).click()
  await expect(nodes).toHaveValue('4')
  await nodes.fill('8')
  await page.getByRole('link', { name: 'Workloads', exact: true }).click()
  await page.getByRole('button', { name: 'Add 1 VM', exact: true }).click()
  await page.getByRole('link', { name: 'Storage Sizing', exact: true }).click()
  await page.getByRole('link', { name: 'Hardware & Drives', exact: true }).click()
  await expect(nodes).toHaveValue('6')
  await page.reload()
  await expect(nodes).toHaveValue('6')
  await expect(page.getByLabel('Active project name')).toHaveValue('Storage only')
  await page.getByRole('button', { name: 'Review copy', exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Review copy', exact: true }).click()
  await page.getByRole('button', { name: 'Copy and open Workload Planning', exact: true }).click()
  await expect(nodes).toHaveValue('6')
  await page.getByRole('link', { name: 'Workloads', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Name VM-1', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Storage Sizing', exact: true }).click()
  await page.getByRole('link', { name: 'Storage Report', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'VM inventory', exact: true })).toHaveCount(0)
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export project JSON', exact: true }).click()
  const project = JSON.parse(await readFile((await (await downloaded).path())!, 'utf8'))
  expect(project.planningArea).toBe('storage')
  expect(project.appVersion).toBe(version)
  expect(project.inputs.inventory).toEqual([])
  expect(project.inputs.hardware.nodeCount).toBe(6)
  await page.getByRole('button', { name: 'Planning assumptions', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Planning assumptions' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath('storage-report.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('workload buying options lead to a fitting configuration and specialized planners remain accessible', async ({ page }) => {
  await page.goto('./#/planning')
  await page.getByRole('link', { name: /Size from workloads/ }).click()
  await page.getByRole('button', { name: 'Add 1 VM', exact: true }).click()
  await page.getByRole('link', { name: /Find hardware options/ }).click()
  await expect(page.getByRole('heading', { name: 'What hardware do I need?', exact: true })).toBeVisible()
  await page.getByLabel('Minimum nodes', { exact: true }).fill('6')
  await page.getByLabel('Maximum nodes', { exact: true }).fill('6')
  await page.screenshot({ path: test.info().outputPath('hardware-options.png'), fullPage: true })
  await page.getByRole('button', { name: /^Use .* · 6 nodes$/ }).first().click()
  await expect(page.getByRole('heading', { name: 'Aggregate capacity fits', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Specialized Workloads', exact: true }).click()
  await page.getByRole('link', { name: 'Virtual desktops (AVD)', exact: true }).click()
  await page.getByLabel('Include AVD in workload demand').check()
  await page.getByRole('link', { name: 'Specialized Workloads', exact: true }).click()
  await page.getByRole('link', { name: 'Kubernetes (AKS)', exact: true }).click()
  await page.getByLabel('Include AKS in workload demand').check()
  await expect(page.getByRole('link', { name: 'Hardware Options', exact: true })).toBeVisible()
})

test('documentation publishes the current release and planning guide', async ({ request }) => {
  const guide = await request.get('docs/guide/planning-areas.html')
  expect(guide.ok()).toBeTruthy()
  expect(await guide.text()).toContain('Storage Sizing')
  const changelog = await request.get('docs/changelog.html')
  expect(changelog.ok()).toBeTruthy()
  expect(await changelog.text()).toContain(version)
})
