/**
 * Markdown exporter.
 *
 * Produces a paste-ready summary suitable for:
 *   - Customer proposals
 *   - GitHub issue / PR comments
 *   - thisismydemo.cloud blog posts
 *
 * Includes all workload scenarios, health check, and quick-start reference.
 */

import type { SurveyorState } from '../state/store'
import { computeCapacity, round2 } from '../engine/capacity'
import { computeVolumeSummary, computeQuickStart } from '../engine/volumes'
import { computeCompute } from '../engine/compute'
import { computeAvd } from '../engine/avd'
import { computeSofs } from '../engine/sofs'
import { computeAks } from '../engine/aks'
import { computeMabs } from '../engine/mabs'
import { computeAllCustomWorkloads } from '../engine/custom-workloads'
import { computeAllServicePresets, getCatalogEntry } from '../engine/service-presets'
import { runHealthCheck } from '../engine/healthcheck'

export function generateMarkdown(state: Pick<SurveyorState, 'hardware' | 'advanced' | 'volumes' | 'avd' | 'sofs' | 'aks' | 'virtualMachines' | 'mabs' | 'avdEnabled' | 'sofsEnabled' | 'mabsEnabled' | 'servicePresets' | 'customWorkloads'>): string {
  const capacity = computeCapacity(state.hardware, state.advanced)
  const summary = computeVolumeSummary(state.volumes, capacity)
  const compute = computeCompute(state.hardware, state.advanced)
  const avd = computeAvd(state.avd, state.advanced.overrides)
  const sofs = computeSofs(state.sofs, state.advanced.overrides)
  const aks = computeAks(state.aks)
  const mabsResult = computeMabs(state.mabs)
  const quickStart = computeQuickStart(capacity)

  // Aggregate workload totals
  let totalVCpus = 0, totalMemoryGB = 0, totalStorageTB = 0
  if (state.avdEnabled) { totalVCpus += avd.totalVCpus; totalMemoryGB += avd.totalMemoryGB; totalStorageTB += avd.totalStorageTB }
  if (state.aks.enabled) { totalVCpus += aks.totalVCpus; totalMemoryGB += aks.totalMemoryGB; totalStorageTB += aks.totalStorageTB }
  if (state.virtualMachines?.enabled) {
    const vm = state.virtualMachines
    let rawVCpus = 0
    for (const group of vm.groups) {
      rawVCpus += group.vmCount * group.vCpusPerVm
      totalMemoryGB += group.vmCount * group.memoryPerVmGB
      totalStorageTB += (group.vmCount * group.storagePerVmGB) / 1024
    }
    totalVCpus += rawVCpus / vm.vCpuOvercommitRatio
  }
  if (state.sofsEnabled) { totalVCpus += sofs.sofsVCpusTotal; totalMemoryGB += sofs.sofsMemoryTotalGB; totalStorageTB += sofs.totalStorageTB }
  if (state.mabsEnabled) { totalVCpus += mabsResult.mabsVCpus; totalMemoryGB += mabsResult.mabsMemoryGB; totalStorageTB += mabsResult.totalStorageTB + mabsResult.mabsOsDiskTB }
  const presetTotals = computeAllServicePresets(state.servicePresets)
  totalVCpus    += presetTotals.totalVCpus
  totalMemoryGB += presetTotals.totalMemoryGB
  totalStorageTB += presetTotals.totalStorageTB
  const customTotals = computeAllCustomWorkloads(state.customWorkloads)
  totalVCpus    += customTotals.totalVCpus
  totalMemoryGB += customTotals.totalMemoryGB
  totalStorageTB += customTotals.totalStorageTB

  const workloadSummary = {
    totalVCpus: Math.round(totalVCpus),
    totalMemoryGB: Math.round(totalMemoryGB),
    totalStorageTB: round2(totalStorageTB),
  }

  const health = runHealthCheck({
    hardware: state.hardware,
    settings: state.advanced,
    volumes: state.volumes,
    capacity,
    compute,
    workloadSummary,
  })

  const lines: string[] = []
  const hw = state.hardware

  lines.push('# Azure Local Cluster Plan')
  lines.push('')
  lines.push(`> Generated by **Azure Local Surveyor** on ${new Date().toLocaleDateString()}`)
  lines.push('')

  // ── Hardware ──
  lines.push('## Cluster Hardware')
  lines.push('')
  lines.push(`| Parameter | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| Nodes | ${hw.nodeCount} |`)
  lines.push(`| Capacity drives/node | ${hw.capacityDrivesPerNode} × ${hw.capacityDriveSizeTB} TB (${hw.capacityMediaType.toUpperCase()}) |`)
  if (hw.cacheDrivesPerNode > 0) {
    lines.push(`| Cache drives/node | ${hw.cacheDrivesPerNode} × ${hw.cacheDriveSizeTB} TB (${hw.cacheMediaType.toUpperCase()}) |`)
  }
  lines.push(`| CPU per node | ${hw.coresPerNode} cores${hw.hyperthreadingEnabled ? ' (HT)' : ''} |`)
  lines.push(`| RAM per node | ${hw.memoryPerNodeGB} GB |`)
  lines.push('')

  // ── Capacity ──
  lines.push('## Capacity')
  lines.push('')
  lines.push(`| Metric | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| Raw pool | ${capacity.rawPoolTB} TB |`)
  lines.push(`| Pool reserve (${capacity.reserveDrives} drives) | ${capacity.reserveTB} TB |`)
  lines.push(`| Available for volumes | ${round2(capacity.availableForVolumesTB)} TB |`)
  lines.push(`| Resiliency | ${capacity.resiliencyType} (${(capacity.resiliencyFactor * 100).toFixed(0)}% efficiency) |`)
  lines.push(`| **Effective usable** | **${round2(capacity.effectiveUsableTB)} TB** |`)
  lines.push('')

  // ── Compute ──
  lines.push('## Compute')
  lines.push('')
  lines.push(`| Metric | All Nodes | N+1 |`)
  lines.push(`|---|---:|---:|`)
  lines.push(`| Usable vCPUs | ${compute.usableVCpus} | ${compute.usableVCpusN1} |`)
  lines.push(`| Usable RAM (GB) | ${compute.usableMemoryGB} | ${compute.usableMemoryGBN1} |`)
  lines.push('')

  // ── Volumes ──
  if (summary.volumes.length > 0) {
    lines.push('## Volumes')
    lines.push('')
    lines.push('| Name | Resiliency | Calculator TB | WAC GB |')
    lines.push('|---|---|---:|---:|')
    for (const v of summary.volumes) {
      lines.push(`| ${v.name} | ${v.resiliency} | ${v.calculatorSizeTB} | ${v.wacSizeGB} |`)
    }
    lines.push('')
    lines.push(`**Storage utilization:** ${summary.utilizationPct}% (${summary.remainingUsableTB} TB remaining)`)
    lines.push('')
  }

  // ── Quick-Start Reference ──
  if (quickStart.rows.length > 0) {
    const row = quickStart.rows[0]
    lines.push('## Quick-Start Volume Reference')
    lines.push('')
    lines.push(`${row.volumeCount} equal volumes of ${row.calculatorSizeTB} TB each (${row.resiliencyLabel})`)
    lines.push('')
    lines.push('```powershell')
    lines.push(quickStart.psScript)
    lines.push('```')
    lines.push('')
  }

  // ── Workloads ──
  const anyWorkloadEnabled = state.avdEnabled || state.aks.enabled
    || state.virtualMachines?.enabled || state.sofsEnabled || state.mabsEnabled
    || presetTotals.totalVCpus > 0 || customTotals.totalVCpus > 0

  if (anyWorkloadEnabled) {
    lines.push('## Workload Summary')
    lines.push('')
    lines.push('| Scenario | vCPUs | Memory (GB) | Storage (TB) |')
    lines.push('|---|---:|---:|---:|')
    if (state.avdEnabled) lines.push(`| AVD | ${avd.totalVCpus} | ${avd.totalMemoryGB} | ${round2(avd.totalStorageTB)} |`)
    if (state.aks.enabled) lines.push(`| AKS | ${aks.totalVCpus} | ${aks.totalMemoryGB} | ${round2(aks.totalStorageTB)} |`)
    if (state.virtualMachines?.enabled) {
      const vm = state.virtualMachines
      const vmVCpus = Math.round(vm.groups.reduce((s, g) => s + g.vmCount * g.vCpusPerVm, 0) / vm.vCpuOvercommitRatio)
      const vmMemory = vm.groups.reduce((s, g) => s + g.vmCount * g.memoryPerVmGB, 0)
      const vmStorage = round2(vm.groups.reduce((s, g) => s + (g.vmCount * g.storagePerVmGB) / 1024, 0))
      lines.push(`| Virtual Machines | ${vmVCpus} | ${vmMemory} | ${vmStorage} |`)
    }
    if (state.sofsEnabled) lines.push(`| SOFS | ${sofs.sofsVCpusTotal} | ${sofs.sofsMemoryTotalGB} | ${round2(sofs.totalStorageTB)} |`)
    if (state.mabsEnabled) lines.push(`| MABS | ${mabsResult.mabsVCpus} | ${mabsResult.mabsMemoryGB} | ${round2(mabsResult.totalStorageTB + mabsResult.mabsOsDiskTB)} |`)
    if (presetTotals.totalVCpus > 0) lines.push(`| Arc-Enabled Services | ${presetTotals.totalVCpus} | ${presetTotals.totalMemoryGB} | ${presetTotals.totalStorageTB} |`)
    if (customTotals.totalVCpus > 0) lines.push(`| Custom Workloads | ${customTotals.totalVCpus} | ${customTotals.totalMemoryGB} | ${customTotals.totalStorageTB} |`)
    lines.push(`| **Total** | **${workloadSummary.totalVCpus}** | **${workloadSummary.totalMemoryGB}** | **${workloadSummary.totalStorageTB}** |`)
    lines.push('')
  }

  // ── AVD Detail ──
  if (state.avdEnabled) {
    lines.push('### AVD Detail')
    lines.push('')
    lines.push(`| Metric | Value |`)
    lines.push(`|---|---|`)
    lines.push(`| Session Host Groups | ${state.avd.pools.length} |`)
    lines.push(`| Users | ${avd.totalUsers}${avd.totalConcurrentUsers > 0 ? ` (${avd.totalConcurrentUsers} concurrent sizing)` : ''} |`)
    lines.push(`| Workload model | ${state.avd.pools.length === 1 ? state.avd.pools[0].workloadType : 'Mixed across session host groups'} |`)
    lines.push(`| Session hosts | ${avd.sessionHostCount} (${avd.usersPerHost} users/host) |`)
    lines.push(`| Limiting factor | ${avd.limitingFactor} |`)
    lines.push(`| Profile storage | ${round2(avd.profileStorageWithGrowthTB)} TB (${state.avd.growthBufferPct}% growth buffer) |`)
    if (avd.totalExternalStorageTB > 0) lines.push(`| External storage | ${round2(avd.totalExternalStorageTB)} TB |`)
    lines.push('')

    if (state.avd.pools.length > 1) {
      lines.push('| Pool | Users | Hosts | Storage Location | Cluster Storage (TB) | External Storage (TB) |')
      lines.push('|---|---:|---:|---|---:|---:|')
      for (const pool of avd.pools) {
        lines.push(`| ${pool.name} | ${pool.totalUsers}${pool.concurrentUsers > 0 ? ` (${pool.concurrentUsers} concurrent)` : ''} | ${pool.sessionHostCount} | ${pool.profileStorageLocation} | ${round2(pool.totalStorageTB)} | ${round2(pool.externalizedStorageTB)} |`)
      }
      lines.push('')
    }
  }

  // ── SOFS Detail ──
  if (state.sofsEnabled) {
    lines.push('### SOFS Detail')
    lines.push('')
    lines.push(`| Metric | Value |`)
    lines.push(`|---|---|`)
    lines.push(`| Users | ${state.sofs.userCount} |`)
    lines.push(`| Profile storage | ${sofs.totalProfileStorageTB} TB |`)
    lines.push(`| Internal mirror | ${state.sofs.internalMirror} (${sofs.internalMirrorFactor}×) |`)
    lines.push(`| Internal footprint | ${sofs.internalFootprintTB} TB |`)
    lines.push(`| Login storm IOPS | ${sofs.totalLoginStormIops} |`)
    lines.push('')
  }

  // ── MABS Detail ──
  if (state.mabsEnabled) {
    lines.push('### MABS Detail')
    lines.push('')
    lines.push(`| Metric | Value |`)
    lines.push(`|---|---|`)
    lines.push(`| Protected data | ${state.mabs.protectedDataTB} TB |`)
    lines.push(`| Retention | ${state.mabs.onPremRetentionDays} days |`)
    lines.push(`| Scratch volume | ${mabsResult.scratchVolumeTB} TB |`)
    lines.push(`| Backup volume | ${mabsResult.backupDataVolumeTB} TB |`)
    lines.push(`| Internal mirror | ${state.mabs.internalMirror} (${mabsResult.internalMirrorFactor}×) |`)
    lines.push(`| Internal footprint | ${mabsResult.internalFootprintTB} TB |`)
    lines.push('')
  }

  // ── Service Presets Detail ──
  const enabledPresets = state.servicePresets.filter((p) => p.enabled && p.instanceCount > 0)
  if (enabledPresets.length > 0) {
    lines.push('### Arc-Enabled Services Detail')
    lines.push('')
    lines.push('| Service | Instances | vCPUs | Memory (GB) | Storage (TB) |')
    lines.push('|---|---:|---:|---:|---:|')
    for (const inst of enabledPresets) {
      const entry = getCatalogEntry(inst.catalogId)
      if (!entry) continue
      const t = { totalVCpus: 0, totalMemoryGB: 0, totalStorageTB: 0 }
      t.totalVCpus   = (inst.vCpusOverride   ?? entry.defaultVCpusPerInstance)    * inst.instanceCount
      t.totalMemoryGB = (inst.memoryGBOverride ?? entry.defaultMemoryGBPerInstance) * inst.instanceCount
      t.totalStorageTB = round2((inst.storageTBOverride ?? entry.defaultStorageTBPerInstance) * inst.instanceCount)
      lines.push(`| ${entry.shortName} | ${inst.instanceCount} | ${t.totalVCpus} | ${t.totalMemoryGB} | ${t.totalStorageTB} |`)
    }
    lines.push('')
  }

  // ── Custom Workloads Detail ──
  const enabledCustom = state.customWorkloads.filter((w) => w.enabled)
  if (enabledCustom.length > 0) {
    lines.push('### Custom Workloads Detail')
    lines.push('')
    lines.push('| Name | VMs | vCPUs | Memory (GB) | Storage (TB) | Mirror |')
    lines.push('|---|---:|---:|---:|---:|---:|')
    for (const w of enabledCustom) {
      const vCpus = w.vmCount * w.vCpusPerVm
      const memGB = w.vmCount * w.memoryPerVmGB
      const osDiskTB = round2((w.vmCount * w.osDiskPerVmGB) / 1024)
      const storeTB = round2(w.storageTB + osDiskTB)
      lines.push(`| ${w.name} | ${w.vmCount} | ${vCpus} | ${memGB} | ${storeTB} | ${w.internalMirrorFactor}× |`)
    }
    lines.push('')
  }

  // ── Health Check ──
  lines.push('## Health Check')
  lines.push('')
  if (health.passed) {
    lines.push('**PASSED** — No errors found.')
  } else {
    lines.push(`**FAILED** — ${health.errorCount} error(s), ${health.warningCount} warning(s)`)
  }
  lines.push('')
  if (health.issues.length > 0) {
    lines.push('| Severity | Message |')
    lines.push('|---|---|')
    for (const issue of health.issues) {
      const badge = issue.severity === 'error' ? '🔴' : issue.severity === 'warning' ? '🟡' : '🔵'
      lines.push(`| ${badge} ${issue.severity.toUpperCase()} | ${issue.message} |`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('*Generated by [Azure Local Surveyor](https://surveyor.azurelocal.cloud)*')

  return lines.join('\n')
}
