/**
 * Markdown exporter.
 *
 * Produces a paste-ready summary suitable for:
 *   - Customer proposals
 *   - GitHub issue / PR comments
 *   - thisismydemo.cloud blog posts
 */

import type { SurveyorState } from '../state/store'
import { computeCapacity } from '../engine/capacity'
import { computeVolumeSummary } from '../engine/volumes'
import { computeCompute } from '../engine/compute'
import { computeAvd } from '../engine/avd'

export function generateMarkdown(state: Pick<SurveyorState, 'hardware' | 'advanced' | 'volumes' | 'avd'>): string {
  const capacity = computeCapacity(state.hardware, state.advanced)
  const summary = computeVolumeSummary(state.volumes, capacity)
  const compute = computeCompute(state.hardware, state.advanced)
  const avd = computeAvd(state.avd, state.advanced.overrides)

  const lines: string[] = []
  const hw = state.hardware

  lines.push('# Azure Local Cluster Plan')
  lines.push('')
  lines.push(`> Generated by **Azure Local Surveyor** on ${new Date().toLocaleDateString()}`)
  lines.push('')

  lines.push('## Cluster Hardware')
  lines.push('')
  lines.push(`| Parameter | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| Nodes | ${hw.nodeCount} |`)
  lines.push(`| Capacity drives/node | ${hw.capacityDrivesPerNode} × ${hw.capacityDriveSizeTB} TB (${hw.capacityMediaType.toUpperCase()}) |`)
  if (hw.cacheDrivesPerNode > 0) {
    lines.push(`| Cache drives/node | ${hw.cacheDrivesPerNode} × ${hw.cacheDriveSizeTB} TB (${hw.cacheMediaType.toUpperCase()}) |`)
  }
  lines.push(`| CPU per node | ${hw.coresPerNode} cores |`)
  lines.push(`| RAM per node | ${hw.memoryPerNodeGB} GB |`)
  lines.push('')

  lines.push('## Capacity')
  lines.push('')
  lines.push(`| Metric | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| Raw pool | ${capacity.rawPoolTB} TB |`)
  lines.push(`| Pool reserve (${capacity.reserveDrives} drives) | ${capacity.reserveTB} TB |`)
  lines.push(`| Resiliency | ${capacity.resiliencyType} |`)
  lines.push(`| **Effective usable** | **${capacity.effectiveUsableTB} TB** |`)
  lines.push('')

  if (summary.volumes.length > 0) {
    lines.push('## Volumes')
    lines.push('')
    lines.push('| Name | Resiliency | Calculator TB | WAC GB |')
    lines.push('|---|---|---:|---:|')
    for (const v of summary.volumes) {
      lines.push(`| ${v.name} | ${v.resiliency} | ${v.calculatorSizeTB} | ${v.wacSizeGB} |`)
    }
    lines.push('')
    lines.push(`**Storage utilization:** ${summary.utilizationPct}%`)
    lines.push('')
  }

  lines.push('## Compute')
  lines.push('')
  lines.push(`| Metric | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| Physical cores | ${compute.physicalCores} |`)
  lines.push(`| Usable vCPUs | ${compute.usableVCpus} |`)
  lines.push(`| Physical RAM | ${compute.physicalMemoryGB} GB |`)
  lines.push(`| Usable RAM | ${compute.usableMemoryGB} GB |`)
  lines.push('')

  lines.push('## AVD Sizing')
  lines.push('')
  lines.push(`| Metric | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| Users | ${state.avd.totalUsers} |`)
  lines.push(`| Workload type | ${state.avd.workloadType} |`)
  lines.push(`| Session hosts | ${avd.sessionHostCount} |`)
  lines.push(`| Users per host | ${avd.usersPerHost} |`)
  lines.push(`| Total vCPUs | ${avd.totalVCpus} |`)
  lines.push(`| Total memory | ${avd.totalMemoryGB} GB |`)
  lines.push(`| Total storage | ${avd.totalStorageTB} TB |`)
  lines.push('')

  lines.push('---')
  lines.push('*Generated by [Azure Local Surveyor](https://surveyor.azurelocal.cloud)*')

  return lines.join('\n')
}
