import type { OemPreset } from '../types'

// Vendor-backed model metadata; numeric values are editable planning examples,
// not a certified or orderable bill of materials. See docs/reference/oem-presets.md.
const DELL_AX_PRESETS: OemPreset[] = [
  {
    id: 'dell-ax-670',
    vendor: 'Dell Technologies',
    model: 'AX-670',
    catalogType: 'premier',
    generation: 'Intel Xeon 6',
    coresPerNode: 32,
    memoryPerNodeGB: 256,
    capacityDrivesPerNode: 6,
    capacityDriveSizeTB: 3.84,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '1U; E3.S NVMe storage.',
    sourceUrl: 'https://www.delltechnologies.com/asset/en-sg/products/converged-infrastructure/technical-support/ax-for-azure-local-spec-sheet.pdf',
    sourceTitle: 'Dell AX for Azure Local specification sheet',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'dell-ax-770',
    vendor: 'Dell Technologies',
    model: 'AX-770',
    catalogType: 'premier',
    generation: 'Intel Xeon 6',
    coresPerNode: 64,
    memoryPerNodeGB: 1024,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; E3.S NVMe storage. GPU options require a separate configuration review.',
    sourceUrl: 'https://www.delltechnologies.com/asset/en-sg/products/converged-infrastructure/technical-support/ax-for-azure-local-spec-sheet.pdf',
    sourceTitle: 'Dell AX for Azure Local specification sheet',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'dell-ax-660',
    vendor: 'Dell Technologies',
    model: 'AX-660',
    catalogType: 'premier',
    generation: 'Intel Xeon 4th/5th Gen',
    coresPerNode: 32,
    memoryPerNodeGB: 256,
    capacityDrivesPerNode: 4,
    capacityDriveSizeTB: 3.84,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '1U; all-NVMe planning configuration.',
    sourceUrl: 'https://www.delltechnologies.com/asset/en-sg/products/converged-infrastructure/technical-support/ax-for-azure-local-spec-sheet.pdf',
    sourceTitle: 'Dell AX for Azure Local specification sheet',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'dell-ax-760',
    vendor: 'Dell Technologies',
    model: 'AX-760',
    catalogType: 'premier',
    generation: 'Intel Xeon 4th/5th Gen',
    coresPerNode: 48,
    memoryPerNodeGB: 512,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; all-NVMe planning configuration.',
    sourceUrl: 'https://www.delltechnologies.com/asset/en-sg/products/converged-infrastructure/technical-support/ax-for-azure-local-spec-sheet.pdf',
    sourceTitle: 'Dell AX for Azure Local specification sheet',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'dell-ax-760-hybrid',
    vendor: 'Dell Technologies',
    model: 'AX-760 (hybrid)',
    catalogType: 'premier',
    generation: 'Intel Xeon 4th/5th Gen',
    coresPerNode: 48,
    memoryPerNodeGB: 512,
    capacityDrivesPerNode: 12,
    capacityDriveSizeTB: 14,
    capacityMediaType: 'hdd',
    cacheDrivesPerNode: 2,
    cacheDriveSizeTB: 1.6,
    cacheMediaType: 'nvme',
    notes: '2U; HDD capacity with NVMe cache.',
    sourceUrl: 'https://www.delltechnologies.com/asset/en-sg/products/converged-infrastructure/technical-support/ax-for-azure-local-spec-sheet.pdf',
    sourceTitle: 'Dell AX for Azure Local specification sheet',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'dell-ax-4510c',
    vendor: 'Dell Technologies',
    model: 'AX-4510c',
    catalogType: 'premier',
    generation: 'Intel Xeon D',
    coresPerNode: 16,
    memoryPerNodeGB: 128,
    capacityDrivesPerNode: 4,
    capacityDriveSizeTB: 3.84,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '1U edge sled in an AX-4000 chassis. Node count means sleds, not enclosures.',
    sourceUrl: 'https://www.delltechnologies.com/asset/en-sg/products/converged-infrastructure/technical-support/ax-for-azure-local-spec-sheet.pdf',
    sourceTitle: 'Dell AX for Azure Local specification sheet',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'dell-ax-4520c',
    vendor: 'Dell Technologies',
    model: 'AX-4520c',
    catalogType: 'premier',
    generation: 'Intel Xeon D',
    coresPerNode: 16,
    memoryPerNodeGB: 256,
    capacityDrivesPerNode: 6,
    capacityDriveSizeTB: 3.84,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U edge sled in an AX-4000 chassis. Node count means sleds, not enclosures.',
    sourceUrl: 'https://www.delltechnologies.com/asset/en-sg/products/converged-infrastructure/technical-support/ax-for-azure-local-spec-sheet.pdf',
    sourceTitle: 'Dell AX for Azure Local specification sheet',
    reviewedAt: '2026-09-10',
  },
]

export default DELL_AX_PRESETS
