import type { OemPreset } from '../types'

// Vendor-backed model metadata; numeric values are editable planning examples,
// not a certified or orderable bill of materials. See docs/reference/oem-presets.md.
const HPE_PROLIANT_PRESETS: OemPreset[] = [
  {
    id: 'hpe-dl380-gen12',
    vendor: 'HPE',
    model: 'ProLiant Compute DL380 Gen12',
    catalogType: 'premier',
    generation: 'Gen12',
    coresPerNode: 64,
    memoryPerNodeGB: 1024,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; E3.S NVMe configuration.',
    sourceUrl: 'https://www.hpe.com/us/en/collaterals/collateral.a50007018enw.html',
    sourceTitle: 'HPE ProLiant for Azure Local QuickSpecs',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'hpe-dl360-gen12',
    vendor: 'HPE',
    model: 'ProLiant Compute DL360 Gen12',
    catalogType: 'premier',
    generation: 'Gen12',
    coresPerNode: 32,
    memoryPerNodeGB: 512,
    capacityDrivesPerNode: 4,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '1U; E3.S NVMe configuration.',
    sourceUrl: 'https://www.hpe.com/us/en/collaterals/collateral.a50007018enw.html',
    sourceTitle: 'HPE ProLiant for Azure Local QuickSpecs',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'hpe-dl380-gen11',
    vendor: 'HPE',
    model: 'ProLiant DL380 Gen11',
    catalogType: 'premier',
    generation: 'Gen11',
    coresPerNode: 32,
    memoryPerNodeGB: 256,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; all-NVMe configuration. Current Azure Local QuickSpecs list flash storage only.',
    sourceUrl: 'https://www.hpe.com/us/en/collaterals/collateral.a50007018enw.html',
    sourceTitle: 'HPE ProLiant for Azure Local QuickSpecs',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'hpe-dl145-gen11',
    vendor: 'HPE',
    model: 'ProLiant DL145 Gen11',
    catalogType: 'premier',
    generation: 'Gen11',
    coresPerNode: 24,
    memoryPerNodeGB: 128,
    capacityDrivesPerNode: 4,
    capacityDriveSizeTB: 3.84,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: 'Compact edge platform with AMD EPYC and E3.S NVMe. HPE reclassified this solution as Premier in May 2026.',
    sourceUrl: 'https://www.hpe.com/us/en/collaterals/collateral.a50007018enw.html',
    sourceTitle: 'HPE ProLiant for Azure Local QuickSpecs',
    reviewedAt: '2026-09-10',
  },
]

export default HPE_PROLIANT_PRESETS
