import type { OemPreset } from '../types'

// Vendor-backed model metadata; numeric values are editable planning examples,
// not a certified or orderable bill of materials. See docs/reference/oem-presets.md.
const LENOVO_MX_PRESETS: OemPreset[] = [
  {
    id: 'lenovo-mx630-v4',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX630 V4',
    catalogType: 'premier',
    generation: 'V4',
    coresPerNode: 48,
    memoryPerNodeGB: 512,
    capacityDrivesPerNode: 4,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '1U; Intel Xeon 6, all-NVMe configuration.',
    sourceUrl: 'https://lenovopress.lenovo.com/lp2136-lenovo-thinkagile-mx630-v4-hyperconverged-system',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'lenovo-mx650-v4',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX650 V4',
    catalogType: 'premier',
    generation: 'V4',
    coresPerNode: 64,
    memoryPerNodeGB: 1024,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; Intel Xeon 6, all-NVMe configuration.',
    sourceUrl: 'https://lenovopress.lenovo.com/lp2137-lenovo-thinkagile-mx650-v4-hyperconverged-system',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'lenovo-mx650a-v4',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX650a V4',
    catalogType: 'premier',
    generation: 'V4',
    coresPerNode: 64,
    memoryPerNodeGB: 1024,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; GPU-focused Intel Xeon 6 platform. This preset sizes local storage, CPU and RAM only.',
    sourceUrl: 'https://lenovopress.lenovo.com/lp2258-lenovo-thinkagile-mx650a-v4-hyperconverged-system',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'lenovo-mx455-v3',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX455 V3 Edge',
    catalogType: 'premier',
    generation: 'V3',
    coresPerNode: 24,
    memoryPerNodeGB: 192,
    capacityDrivesPerNode: 4,
    capacityDriveSizeTB: 3.84,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U short-depth edge platform; AMD EPYC 8004 and NVMe storage.',
    sourceUrl: 'https://lenovopress.lenovo.com/lp1889-thinkagile-mx455-v3-edge-premier-solution',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'lenovo-mx650-v3-premier',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX650 V3 (Premier)',
    catalogType: 'premier',
    generation: 'V3',
    coresPerNode: 48,
    memoryPerNodeGB: 512,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; all-NVMe Premier configuration (machine type 7DKB).',
    sourceUrl: 'https://lenovopress.lenovo.com/lp1675-thinkagile-mx650-v3-2u-integrated-system-and-certified-node-4th-generation',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'lenovo-mx630-v3',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX630 V3',
    catalogType: 'integrated',
    generation: 'V3',
    coresPerNode: 32,
    memoryPerNodeGB: 256,
    capacityDrivesPerNode: 4,
    capacityDriveSizeTB: 3.84,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '1U; all-NVMe Integrated System configuration.',
    sourceUrl: 'https://lenovopress.lenovo.com/lp1674-thinkagile-mx630-v3-1u-integrated-system-and-certified-node-4th-generation',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'lenovo-mx650-v3',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX650 V3',
    catalogType: 'integrated',
    generation: 'V3',
    coresPerNode: 48,
    memoryPerNodeGB: 512,
    capacityDrivesPerNode: 8,
    capacityDriveSizeTB: 7.68,
    capacityMediaType: 'nvme',
    cacheDrivesPerNode: 0,
    cacheDriveSizeTB: 0,
    cacheMediaType: 'none',
    notes: '2U; all-NVMe Integrated System configuration (machine type 7D6S).',
    sourceUrl: 'https://lenovopress.lenovo.com/lp1675-thinkagile-mx650-v3-2u-integrated-system-and-certified-node-4th-generation',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
  {
    id: 'lenovo-mx650-v3-hybrid',
    vendor: 'Lenovo',
    model: 'ThinkAgile MX650 V3 (hybrid)',
    catalogType: 'integrated',
    generation: 'V3',
    coresPerNode: 48,
    memoryPerNodeGB: 512,
    capacityDrivesPerNode: 12,
    capacityDriveSizeTB: 14,
    capacityMediaType: 'hdd',
    cacheDrivesPerNode: 2,
    cacheDriveSizeTB: 1.6,
    cacheMediaType: 'nvme',
    notes: '2U; HDD capacity and NVMe cache. Select the Integrated System offering, whose options differ from Premier.',
    sourceUrl: 'https://lenovopress.lenovo.com/lp1675-thinkagile-mx650-v3-2u-integrated-system-and-certified-node-4th-generation',
    sourceTitle: 'Lenovo product guide',
    reviewedAt: '2026-09-10',
  },
]

export default LENOVO_MX_PRESETS
